[package]
name = "terminus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf_rs = "0.1.3"
structopt = "0.3.13"
crossterm = "0.22.1"
